from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Mapping

from .config import ManagerPaths
from .models import InstallInfo
from .util import (
    LLVMManagerError,
    atomic_write_text,
    file_lock,
    read_json,
    run,
    write_json,
)

SYSTEM_CXX_STANDARD_LIBRARY = "system"
MANAGED_LIBCXX_STANDARD_LIBRARY = "managed-libc++"
CXX_STANDARD_LIBRARY_CHOICES = (
    SYSTEM_CXX_STANDARD_LIBRARY,
    MANAGED_LIBCXX_STANDARD_LIBRARY,
)

_MANAGED_LIBCXX_RUNTIMES = ("libcxx", "libcxxabi", "libunwind")
_TARGET_TRIPLE_RE = re.compile(r"^[A-Za-z0-9_.+-]+$")
_CONFIG_MARKER = "# Generated by llvm-manager. Use --no-default-config to bypass this pairing."


def validate_standard_library(selection: str) -> None:
    if selection not in CXX_STANDARD_LIBRARY_CHOICES:
        raise LLVMManagerError(f"Unsupported C++ standard library selection: {selection}")
    if selection == MANAGED_LIBCXX_STANDARD_LIBRARY and os.name == "nt":
        raise LLVMManagerError("Managed libc++ pairing is not currently supported on Windows")


def standard_library_runtimes(
    selection: str,
    runtimes: tuple[str, ...],
) -> tuple[str, ...]:
    result = list(dict.fromkeys(runtime for runtime in runtimes if runtime))
    if selection == MANAGED_LIBCXX_STANDARD_LIBRARY:
        result.extend(runtime for runtime in _MANAGED_LIBCXX_RUNTIMES if runtime not in result)
    return tuple(result)


def standard_library_cmake_options(selection: str) -> tuple[str, ...]:
    if selection == MANAGED_LIBCXX_STANDARD_LIBRARY:
        return ("-DLIBCXXABI_USE_LLVM_UNWINDER=ON",)
    return ()


def _target_triple(clangxx: Path, env: Mapping[str, str]) -> str:
    for option in ("--print-target-triple", "-dumpmachine"):
        completed = run([clangxx, option], capture=True, check=False, env=env)
        output = completed.stdout.strip()
        triple = output.splitlines()[0] if output else ""
        if completed.returncode == 0 and triple and _TARGET_TRIPLE_RE.fullmatch(triple):
            return triple
    raise LLVMManagerError(f"Could not determine the installed compiler target triple: {clangxx}")


def _has_libcxx_library(directory: Path) -> bool:
    try:
        return any(directory.glob("libc++.*"))
    except OSError:
        return False


def _libcxx_header_directory(prefix: Path, triple: str) -> Path:
    candidates = (
        prefix / "include" / "c++" / "v1",
        prefix / "include" / triple / "c++" / "v1",
    )
    for candidate in candidates:
        if candidate.is_dir():
            return candidate
    raise LLVMManagerError(
        "Managed libc++ was requested, but its installed headers were not found under "
        f"{prefix / 'include'}"
    )


def _libcxx_library_directory(prefix: Path) -> Path:
    roots = (prefix / "lib", prefix / "lib64")
    for root in roots:
        if root.is_dir() and _has_libcxx_library(root):
            return root

    for root in roots:
        if not root.is_dir():
            continue
        try:
            children = sorted(
                (child for child in root.iterdir() if child.is_dir()),
                key=lambda path: path.name,
            )
        except OSError:
            continue
        for child in children:
            if _has_libcxx_library(child):
                return child

    raise LLVMManagerError(
        f"Managed libc++ was requested, but no installed libc++ library was found under {prefix}"
    )


def _config_relative_path(path: Path, config_directory: Path) -> str:
    relative = os.path.relpath(path, config_directory).replace(os.sep, "/")
    return f"<CFGDIR>/{relative}"


def _config_path_token(path: str) -> str:
    if not any(character.isspace() for character in path):
        return path
    escaped = path.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _metadata_relative_path(path: Path, prefix: Path) -> str:
    return os.path.relpath(path, prefix).replace(os.sep, "/")


def _relative_metadata_path(prefix: Path, value: object, description: str) -> Path:
    if not isinstance(value, str) or not value:
        raise LLVMManagerError(f"Managed libc++ metadata has no {description} path")
    root = prefix.resolve()
    candidate = (root / value).resolve()
    try:
        candidate.relative_to(root)
    except ValueError as error:
        raise LLVMManagerError(
            f"Managed libc++ metadata points outside its installation: {candidate}"
        ) from error
    return candidate


def managed_libcxx_from_metadata(metadata: Mapping[str, object]) -> dict[str, object] | None:
    available = metadata.get("managed_cxx_standard_library")
    if isinstance(available, dict) and available.get("kind") == MANAGED_LIBCXX_STANDARD_LIBRARY:
        return dict(available)

    # Compatibility with 1.7.0 installs, where the selected standard library
    # also served as the only record that the prefix contains managed runtimes.
    selected = metadata.get("cxx_standard_library")
    if not isinstance(selected, dict) or selected.get("kind") != MANAGED_LIBCXX_STANDARD_LIBRARY:
        return None
    provider_prefix = selected.get("provider_prefix")
    if provider_prefix not in (None, "", "."):
        return None
    if not isinstance(selected.get("headers"), str) or not isinstance(selected.get("libraries"), str):
        return None
    return {
        "kind": MANAGED_LIBCXX_STANDARD_LIBRARY,
        "target": selected.get("provider_target", selected.get("target")),
        "headers": selected["headers"],
        "libraries": selected["libraries"],
        "runtimes": list(selected.get("runtimes", _MANAGED_LIBCXX_RUNTIMES)),
    }


def managed_libcxx_capability(selection: Mapping[str, object]) -> dict[str, object]:
    return {
        "kind": MANAGED_LIBCXX_STANDARD_LIBRARY,
        "target": selection.get("provider_target", selection.get("target")),
        "headers": selection["headers"],
        "libraries": selection["libraries"],
        "runtimes": list(selection.get("runtimes", _MANAGED_LIBCXX_RUNTIMES)),
    }


def _provider_paths(
    provider_prefix: Path,
    capability: Mapping[str, object],
) -> tuple[Path, Path]:
    headers = _relative_metadata_path(provider_prefix, capability.get("headers"), "header")
    libraries = _relative_metadata_path(provider_prefix, capability.get("libraries"), "library")
    if not headers.is_dir():
        raise LLVMManagerError(f"Managed libc++ headers are missing: {headers}")
    if not libraries.is_dir() or not _has_libcxx_library(libraries):
        raise LLVMManagerError(f"Managed libc++ libraries are missing: {libraries}")
    return headers, libraries


def _local_managed_libcxx_capability(prefix: Path, triple: str) -> dict[str, object]:
    headers = _libcxx_header_directory(prefix, triple)
    libraries = _libcxx_library_directory(prefix)
    return {
        "kind": MANAGED_LIBCXX_STANDARD_LIBRARY,
        "target": triple,
        "headers": str(headers.relative_to(prefix)),
        "libraries": str(libraries.relative_to(prefix)),
        "runtimes": list(_MANAGED_LIBCXX_RUNTIMES),
    }


def _write_managed_libcxx_config(
    compiler_prefix: Path,
    major: int,
    env: Mapping[str, str],
    provider_prefix: Path,
    capability: Mapping[str, object],
    *,
    provider_version: str | None = None,
    provider_tag: str | None = None,
    compiler_target: str | None = None,
) -> tuple[dict[str, object], Path]:
    suffix = ".exe" if os.name == "nt" else ""
    clangxx = compiler_prefix / "bin" / f"clang++-{major}{suffix}"
    triple = compiler_target or _target_triple(clangxx, env)
    headers, libraries = _provider_paths(provider_prefix, capability)
    config = compiler_prefix / "bin" / f"{triple}-clang++.cfg"
    header_flag = _config_relative_path(headers, config.parent)
    library_flag = _config_relative_path(libraries, config.parent)
    atomic_write_text(
        config,
        f"{_CONFIG_MARKER}\n"
        "-stdlib=libc++\n"
        "-nostdinc++\n"
        f"-isystem {_config_path_token(header_flag)}\n"
        f"-L {_config_path_token(library_flag)}\n"
        f"-Wl,-rpath,{_config_path_token(library_flag)}\n",
    )
    selection: dict[str, object] = {
        "kind": MANAGED_LIBCXX_STANDARD_LIBRARY,
        "target": triple,
        "provider_target": capability.get("target"),
        "provider_prefix": _metadata_relative_path(provider_prefix.resolve(), compiler_prefix.resolve()),
        "headers": capability["headers"],
        "libraries": capability["libraries"],
        "config": str(config.relative_to(compiler_prefix)),
        "runtimes": list(capability.get("runtimes", _MANAGED_LIBCXX_RUNTIMES)),
    }
    if provider_version:
        selection["provider_version"] = provider_version
    if provider_tag:
        selection["provider_tag"] = provider_tag
    return selection, config


def configure_standard_library(
    prefix: Path,
    major: int,
    env: Mapping[str, str],
    selection: str,
) -> tuple[dict[str, object], list[Path]]:
    if selection == SYSTEM_CXX_STANDARD_LIBRARY:
        return {"kind": SYSTEM_CXX_STANDARD_LIBRARY}, []
    if selection == MANAGED_LIBCXX_STANDARD_LIBRARY:
        suffix = ".exe" if os.name == "nt" else ""
        triple = _target_triple(prefix / "bin" / f"clang++-{major}{suffix}", env)
        capability = _local_managed_libcxx_capability(prefix, triple)
        configured, config = _write_managed_libcxx_config(
            prefix,
            major,
            env,
            prefix,
            capability,
            compiler_target=triple,
        )
        return configured, [config]
    raise LLVMManagerError(f"Unsupported C++ standard library selection: {selection}")


def _selected_config(prefix: Path, metadata: Mapping[str, object]) -> Path | None:
    selected = metadata.get("cxx_standard_library")
    if not isinstance(selected, dict) or selected.get("kind") != MANAGED_LIBCXX_STANDARD_LIBRARY:
        return None
    value = selected.get("config")
    if not isinstance(value, str) or not value:
        return None
    root = prefix.resolve()
    candidate = (root / value).resolve()
    try:
        candidate.relative_to(root)
    except ValueError:
        return None
    return candidate


def _is_manager_config(path: Path) -> bool:
    try:
        return path.is_file() and path.read_text(encoding="utf-8").startswith(_CONFIG_MARKER)
    except OSError:
        return False


def _restore_file(path: Path, contents: str | None) -> None:
    if contents is None:
        try:
            path.unlink()
        except FileNotFoundError:
            pass
    else:
        atomic_write_text(path, contents)


def switch_standard_library(
    paths: ManagerPaths,
    compiler: InstallInfo,
    provider: InstallInfo | None,
    *,
    env: Mapping[str, str] | None = None,
) -> dict[str, object]:
    if not compiler.managed:
        raise LLVMManagerError("The selected compiler is not managed by llvm-manager")
    if compiler.version is None:
        raise LLVMManagerError("The selected compiler version could not be determined")
    if os.name == "nt" and provider is not None:
        raise LLVMManagerError("Managed libc++ pairing is not currently supported on Windows")

    compiler_prefix = compiler.prefix.resolve()
    metadata_path = compiler_prefix / ".llvm-manager.json"
    environment = dict(env or os.environ)

    with file_lock(paths.lock_file):
        original_metadata_text = metadata_path.read_text(encoding="utf-8")
        metadata_value = read_json(metadata_path, {}, strict=True)
        if not isinstance(metadata_value, dict):
            raise LLVMManagerError(f"Invalid llvm-manager metadata: {metadata_path}")
        metadata = dict(metadata_value)

        local_capability = managed_libcxx_from_metadata(metadata)
        previous_config = _selected_config(compiler_prefix, metadata)
        previous_config_text = (
            previous_config.read_text(encoding="utf-8")
            if previous_config is not None and previous_config.is_file()
            else None
        )
        new_config: Path | None = None

        state_existed = paths.state_file.is_file()
        original_state_text = paths.state_file.read_text(encoding="utf-8") if state_existed else None

        try:
            if provider is None:
                selected: dict[str, object] = {"kind": SYSTEM_CXX_STANDARD_LIBRARY}
                if previous_config is not None and _is_manager_config(previous_config):
                    previous_config.unlink()
            else:
                if not provider.managed:
                    raise LLVMManagerError("The selected libc++ provider is not managed by llvm-manager")
                provider_metadata_value = read_json(
                    provider.prefix / ".llvm-manager.json",
                    {},
                    strict=True,
                )
                if not isinstance(provider_metadata_value, dict):
                    raise LLVMManagerError(
                        f"Invalid llvm-manager metadata: {provider.prefix / '.llvm-manager.json'}"
                    )
                capability = managed_libcxx_from_metadata(provider_metadata_value)
                if capability is None:
                    raise LLVMManagerError(f"{provider.label} does not contain a managed libc++ installation")
                selected, new_config = _write_managed_libcxx_config(
                    compiler_prefix,
                    compiler.version.major,
                    environment,
                    provider.prefix.resolve(),
                    capability,
                    provider_version=provider.version.display if provider.version else None,
                    provider_tag=provider.tag,
                )
                if (
                    previous_config is not None
                    and previous_config != new_config
                    and _is_manager_config(previous_config)
                ):
                    previous_config.unlink()

            if local_capability is not None:
                metadata["managed_cxx_standard_library"] = local_capability
            schema_version = metadata.get("schema_version")
            metadata["schema_version"] = max(schema_version if isinstance(schema_version, int) else 0, 4)
            metadata["cxx_standard_library"] = selected

            installed = metadata.get("installed_files")
            installed_files = {
                item for item in installed if isinstance(item, str)
            } if isinstance(installed, list) else set()
            if previous_config is not None:
                try:
                    installed_files.discard(str(previous_config.relative_to(compiler_prefix)))
                except ValueError:
                    pass
            if new_config is not None:
                installed_files.add(str(new_config.relative_to(compiler_prefix)))
            metadata["installed_files"] = sorted(installed_files)
            write_json(metadata_path, metadata)

            if compiler.active:
                state_value = read_json(paths.state_file, {})
                state = dict(state_value) if isinstance(state_value, dict) else {}
                state.update(
                    {
                        "active_prefix": str(compiler_prefix),
                        "version": compiler.version.display,
                        "tag": compiler.tag,
                        "cxx_standard_library": selected["kind"],
                        "cxx_standard_library_version": selected.get("provider_version"),
                    }
                )
                write_json(paths.state_file, state)
        except Exception:
            atomic_write_text(metadata_path, original_metadata_text)
            if previous_config is not None:
                _restore_file(previous_config, previous_config_text)
            if new_config is not None and new_config != previous_config:
                _restore_file(new_config, None)
            elif new_config is not None and previous_config_text is None:
                _restore_file(new_config, None)
            if state_existed and original_state_text is not None:
                atomic_write_text(paths.state_file, original_state_text)
            elif paths.state_file.exists():
                paths.state_file.unlink()
            raise

        return selected
