from __future__ import annotations

import os
import shutil
from pathlib import Path

from .config import ManagerPaths
from .models import InstallInfo
from .util import LLVMManagerError, quote_posix, replace_managed_block, write_json


def _replace_symlink(link: Path, target: Path) -> None:
    if link.exists() and not link.is_symlink():
        raise LLVMManagerError(
            f"Cannot replace {link}: it exists and is not a symbolic link. Move it aside and retry."
        )
    temporary = link.with_name(f".{link.name}.new")
    if temporary.exists() or temporary.is_symlink():
        if temporary.is_dir() and not temporary.is_symlink():
            shutil.rmtree(temporary)
        else:
            temporary.unlink()
    temporary.symlink_to(target, target_is_directory=True)
    temporary.replace(link)


def _shell_kind(shell: str | None) -> str:
    name = Path(shell or os.environ.get("SHELL", "")).name.lower()
    if name == "fish":
        return "fish"
    if name in {"zsh", "bash", "sh", "dash", "ksh"}:
        return name
    return "profile"


def _profile_path(paths: ManagerPaths, kind: str, explicit: Path | None) -> Path:
    if explicit:
        return explicit.expanduser().resolve()
    if kind == "fish":
        return paths.home / ".config" / "fish" / "config.fish"
    if kind == "zsh":
        return paths.home / ".zshrc"
    if kind == "bash":
        return paths.home / ".bashrc"
    return paths.home / ".profile"


def _write_activation_scripts(
    paths: ManagerPaths,
    selected_prefix: Path,
    clang_name: str,
    clangxx_name: str,
) -> None:
    llvm_home = paths.current if paths.current.is_symlink() else selected_prefix
    sh_home = quote_posix(llvm_home)
    paths.activation_sh.write_text(
        "# Generated by llvm-manager. Source this file to activate the selected LLVM.\n"
        f"export LLVM_HOME={sh_home}\n"
        'export PATH="$LLVM_HOME/bin:$PATH"\n'
        f'export CC="$LLVM_HOME/bin/{clang_name}"\n'
        f'export CXX="$LLVM_HOME/bin/{clangxx_name}"\n',
        encoding="utf-8",
    )
    paths.activation_fish.write_text(
        "# Generated by llvm-manager. Source this file to activate the selected LLVM.\n"
        f"set -gx LLVM_HOME {sh_home}\n"
        'fish_add_path --prepend "$LLVM_HOME/bin"\n'
        f'set -gx CC "$LLVM_HOME/bin/{clang_name}"\n'
        f'set -gx CXX "$LLVM_HOME/bin/{clangxx_name}"\n',
        encoding="utf-8",
    )
    escaped = str(llvm_home).replace("'", "''")
    paths.activation_ps1.write_text(
        "# Generated by llvm-manager. Dot-source this file to activate the selected LLVM.\n"
        f"$env:LLVM_HOME = '{escaped}'\n"
        '$env:Path = "$env:LLVM_HOME\\bin;$env:Path"\n'
        f'$env:CC = "$env:LLVM_HOME\\bin\\{clang_name}"\n'
        f'$env:CXX = "$env:LLVM_HOME\\bin\\{clangxx_name}"\n',
        encoding="utf-8",
    )


def _update_windows_environment(selected_prefix: Path, clang_name: str, clangxx_name: str) -> None:
    try:
        import ctypes
        import winreg
    except ImportError as error:  # pragma: no cover - Windows only
        raise LLVMManagerError("Windows environment support is unavailable") from error

    bin_dir = str(selected_prefix / "bin")
    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_READ | winreg.KEY_WRITE) as key:
        try:
            current_path, path_type = winreg.QueryValueEx(key, "Path")
        except FileNotFoundError:
            current_path, path_type = "", winreg.REG_EXPAND_SZ
        entries = [entry for entry in current_path.split(";") if entry]
        entries = [entry for entry in entries if "llvm-manager" not in entry.lower() and entry.lower() != bin_dir.lower()]
        winreg.SetValueEx(key, "Path", 0, path_type, ";".join([bin_dir, *entries]))
        winreg.SetValueEx(key, "LLVM_HOME", 0, winreg.REG_SZ, str(selected_prefix))
        winreg.SetValueEx(key, "CC", 0, winreg.REG_SZ, str(selected_prefix / "bin" / clang_name))
        winreg.SetValueEx(key, "CXX", 0, winreg.REG_SZ, str(selected_prefix / "bin" / clangxx_name))

    HWND_BROADCAST = 0xFFFF
    WM_SETTINGCHANGE = 0x001A
    ctypes.windll.user32.SendMessageTimeoutW(
        HWND_BROADCAST,
        WM_SETTINGCHANGE,
        0,
        "Environment",
        0x0002,
        5000,
        None,
    )


def switch_install(
    paths: ManagerPaths,
    install: InstallInfo,
    *,
    shell: str | None = None,
    profile: Path | None = None,
) -> Path | None:
    paths.ensure()
    selected_prefix = install.prefix.resolve()
    if not (selected_prefix / "bin").is_dir():
        raise LLVMManagerError(f"Selected LLVM prefix has no bin directory: {selected_prefix}")

    clang_name = install.clang.name
    suffix = Path(clang_name).suffix if os.name == "nt" else ""
    if clang_name.startswith("clang-"):
        version_suffix = Path(clang_name).stem.removeprefix("clang-")
        candidate_cxx = f"clang++-{version_suffix}{suffix}"
    else:
        candidate_cxx = f"clang++{suffix}"
    clangxx_name = candidate_cxx if (selected_prefix / "bin" / candidate_cxx).exists() else clang_name

    if os.name == "nt":  # pragma: no cover - exercised on Windows
        _update_windows_environment(selected_prefix, clang_name, clangxx_name)
        updated_profile = None
    else:
        _replace_symlink(paths.current, selected_prefix)
        kind = _shell_kind(shell)
        updated_profile = _profile_path(paths, kind, profile)
        activation = paths.activation_fish if kind == "fish" else paths.activation_sh
        if kind == "fish":
            block = (
                "# >>> llvm-manager >>>\n"
                f"test -f {quote_posix(activation)}; and source {quote_posix(activation)}\n"
                "# <<< llvm-manager <<<"
            )
        else:
            block = (
                "# >>> llvm-manager >>>\n"
                f"[ -f {quote_posix(activation)} ] && . {quote_posix(activation)}\n"
                "# <<< llvm-manager <<<"
            )
        replace_managed_block(updated_profile, block)

    _write_activation_scripts(paths, selected_prefix, clang_name, clangxx_name)
    write_json(
        paths.state_file,
        {
            "active_prefix": str(selected_prefix),
            "version": install.version.display if install.version else None,
            "tag": install.tag,
        },
    )
    return updated_profile
