from __future__ import annotations

import os
import tempfile
from pathlib import Path
from typing import Callable

from .config import ManagerPaths
from .models import InstallInfo
from .util import (
    LLVMManagerError,
    atomic_write_text,
    file_lock,
    quote_fish,
    quote_posix,
    read_json,
    replace_managed_block,
    write_json,
)

_BEGIN = "# >>> llvm-manager >>>"
_END = "# <<< llvm-manager <<<"


def _replace_symlink(link: Path, target: Path) -> None:
    if link.exists() and not link.is_symlink():
        raise LLVMManagerError(
            f"Cannot replace {link}: it exists and is not a symbolic link. Move it aside and retry."
        )
    link.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(tempfile.mktemp(prefix=f".{link.name}.", suffix=".new", dir=link.parent))
    try:
        temporary.symlink_to(target, target_is_directory=True)
        os.replace(temporary, link)
    finally:
        if temporary.is_symlink() or temporary.exists():
            temporary.unlink()


def _restore_symlink(link: Path, previous: Path | None) -> None:
    if previous is None:
        if link.is_symlink() or link.exists():
            link.unlink()
        return
    _replace_symlink(link, previous)


def _shell_kind(shell: str | None) -> str:
    name = Path(shell or os.environ.get("SHELL", "")).name.lower()
    if name == "fish":
        return "fish"
    if name in {"pwsh", "powershell", "powershell.exe"}:
        return "powershell"
    if name in {"zsh", "bash", "sh", "dash", "ksh"}:
        return name
    return "profile"


def _profile_path(paths: ManagerPaths, kind: str, explicit: Path | None) -> Path:
    if explicit:
        return explicit.expanduser().resolve()
    if kind == "fish":
        return paths.home / ".config" / "fish" / "config.fish"
    if kind == "zsh":
        return paths.home / ".zshrc"
    if kind == "bash":
        bashrc = paths.home / ".bashrc"
        bash_profile = paths.home / ".bash_profile"
        return bash_profile if bash_profile.exists() and not bashrc.exists() else bashrc
    return paths.home / ".profile"


def activation_script(paths: ManagerPaths, shell: str | None = None) -> Path:
    kind = _shell_kind(shell)
    if kind == "fish":
        return paths.activation_fish
    if kind == "powershell" or (os.name == "nt" and shell is None):
        return paths.activation_ps1
    return paths.activation_sh


def _activation_contents(
    paths: ManagerPaths,
    selected_prefix: Path,
    clang_name: str,
    clangxx_name: str,
) -> dict[Path, str]:
    llvm_home = selected_prefix if os.name == "nt" else paths.current
    sh_home = quote_posix(llvm_home)
    fish_home = quote_fish(llvm_home)
    escaped = str(llvm_home).replace("'", "''")
    return {
        paths.activation_sh: (
            "# Generated by llvm-manager. Source this file to activate the selected LLVM.\n"
            f"export LLVM_HOME={sh_home}\n"
            'export PATH="$LLVM_HOME/bin:$PATH"\n'
            f'export CC="$LLVM_HOME/bin/{clang_name}"\n'
            f'export CXX="$LLVM_HOME/bin/{clangxx_name}"\n'
        ),
        paths.activation_fish: (
            "# Generated by llvm-manager. Source this file to activate the selected LLVM.\n"
            f"set -gx LLVM_HOME {fish_home}\n"
            'fish_add_path --prepend "$LLVM_HOME/bin"\n'
            f'set -gx CC "$LLVM_HOME/bin/{clang_name}"\n'
            f'set -gx CXX "$LLVM_HOME/bin/{clangxx_name}"\n'
        ),
        paths.activation_ps1: (
            "# Generated by llvm-manager. Dot-source this file to activate the selected LLVM.\n"
            f"$env:LLVM_HOME = '{escaped}'\n"
            '$env:Path = "$env:LLVM_HOME\\bin;$env:Path"\n'
            f'$env:CC = "$env:LLVM_HOME\\bin\\{clang_name}"\n'
            f'$env:CXX = "$env:LLVM_HOME\\bin\\{clangxx_name}"\n'
        ),
    }


def _write_activation_scripts(contents: dict[Path, str]) -> Callable[[], None]:
    previous: dict[Path, str | None] = {}
    for path, text in contents.items():
        previous[path] = path.read_text(encoding="utf-8") if path.exists() else None
        atomic_write_text(path, text)

    def restore() -> None:
        for path, text in previous.items():
            if text is None:
                try:
                    path.unlink()
                except FileNotFoundError:
                    pass
            else:
                atomic_write_text(path, text)

    return restore


def _profile_block(kind: str, activation: Path) -> str:
    quoted = quote_fish(activation) if kind == "fish" else quote_posix(activation)
    if kind == "fish":
        source = f"test -f {quoted}; and source {quoted}"
    else:
        source = f"[ -f {quoted} ] && . {quoted}"
    return f"{_BEGIN}\n{source}\n{_END}"


def _normalized_windows_path(value: str) -> str:
    return os.path.normcase(os.path.normpath(os.path.expandvars(value.strip().strip('"'))))


def _update_windows_environment(
    paths: ManagerPaths,
    selected_prefix: Path,
    clang_name: str,
    clangxx_name: str,
) -> Callable[[], None]:
    try:
        import ctypes
        import winreg
    except ImportError as error:  # pragma: no cover - Windows only
        raise LLVMManagerError("Windows environment support is unavailable") from error

    names = ("Path", "LLVM_HOME", "CC", "CXX")
    previous: dict[str, tuple[str, int] | None] = {}
    state = read_json(paths.state_file, {})
    old_prefix = None
    if isinstance(state, dict) and isinstance(state.get("active_prefix"), str):
        old_prefix = Path(state["active_prefix"]).expanduser()

    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_READ | winreg.KEY_WRITE) as key:
        for name in names:
            try:
                previous[name] = winreg.QueryValueEx(key, name)
            except FileNotFoundError:
                previous[name] = None

        current_path, path_type = previous["Path"] or ("", winreg.REG_EXPAND_SZ)
        new_bin = str(selected_prefix / "bin")
        removals = {_normalized_windows_path(new_bin)}
        if old_prefix is not None:
            removals.add(_normalized_windows_path(str(old_prefix / "bin")))
        entries = [entry for entry in current_path.split(";") if entry]
        entries = [entry for entry in entries if _normalized_windows_path(entry) not in removals]
        winreg.SetValueEx(key, "Path", 0, path_type, ";".join([new_bin, *entries]))
        winreg.SetValueEx(key, "LLVM_HOME", 0, winreg.REG_SZ, str(selected_prefix))
        winreg.SetValueEx(key, "CC", 0, winreg.REG_SZ, str(selected_prefix / "bin" / clang_name))
        winreg.SetValueEx(key, "CXX", 0, winreg.REG_SZ, str(selected_prefix / "bin" / clangxx_name))

    def restore() -> None:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_WRITE) as key:
            for name, value in previous.items():
                if value is None:
                    try:
                        winreg.DeleteValue(key, name)
                    except FileNotFoundError:
                        pass
                else:
                    winreg.SetValueEx(key, name, 0, value[1], value[0])

    ctypes.windll.user32.SendMessageTimeoutW(
        0xFFFF,
        0x001A,
        0,
        "Environment",
        0x0002,
        5000,
        None,
    )
    return restore


def _compiler_names(install: InstallInfo) -> tuple[str, str]:
    clang_name = install.clang.name
    suffix = Path(clang_name).suffix if os.name == "nt" else ""
    if clang_name.startswith("clang-"):
        version_suffix = Path(clang_name).stem.removeprefix("clang-")
        candidate_cxx = f"clang++-{version_suffix}{suffix}"
    else:
        candidate_cxx = f"clang++{suffix}"
    clangxx_name = candidate_cxx if (install.prefix / "bin" / candidate_cxx).exists() else clang_name
    return clang_name, clangxx_name


def switch_install(
    paths: ManagerPaths,
    install: InstallInfo,
    *,
    shell: str | None = None,
    profile: Path | None = None,
) -> Path | None:
    paths.ensure_root()
    selected_prefix = install.prefix.resolve()
    if not (selected_prefix / "bin").is_dir():
        raise LLVMManagerError(f"Selected LLVM prefix has no bin directory: {selected_prefix}")
    clang_name, clangxx_name = _compiler_names(install)

    with file_lock(paths.lock_file):
        restore_scripts = _write_activation_scripts(
            _activation_contents(paths, selected_prefix, clang_name, clangxx_name)
        )
        state = {
            "active_prefix": str(selected_prefix),
            "version": install.version.display if install.version else None,
            "tag": install.tag,
            "cxx_standard_library": install.cxx_standard_library,
            "cxx_standard_library_version": install.cxx_standard_library_version,
        }

        if os.name == "nt":  # pragma: no cover - exercised on Windows
            rollback = _update_windows_environment(paths, selected_prefix, clang_name, clangxx_name)
            try:
                write_json(paths.state_file, state)
            except Exception:
                rollback()
                restore_scripts()
                raise
            return None

        kind = _shell_kind(shell)
        updated_profile = _profile_path(paths, kind, profile)
        activation = paths.activation_fish if kind == "fish" else paths.activation_sh
        profile_existed = updated_profile.exists()
        previous_profile = updated_profile.read_text(encoding="utf-8") if profile_existed else ""
        previous_target = paths.current.resolve() if paths.current.is_symlink() else None

        try:
            _replace_symlink(paths.current, selected_prefix)
            replace_managed_block(updated_profile, _profile_block(kind, activation))
            write_json(paths.state_file, state)
        except Exception:
            _restore_symlink(paths.current, previous_target)
            if profile_existed:
                atomic_write_text(updated_profile, previous_profile)
            elif updated_profile.exists():
                updated_profile.unlink()
            restore_scripts()
            raise
        return updated_profile
